WiP [OS-524] Add IAM option to SDS Docker
open-io/dockerfiles pull request #118
Opened 2020-05-18 09:06 UTC by dduportal

Signed-off-by: dduportal <damien.duportal@openio.io>

WiP

2020-05-18 17:17 UTC, cdelgehier commented on openio-sds/18.10/openio-docker-init.sh
> +    # Insert "iam" before swift3 in pipeline's setup
I think we can activate the IAM as default and add these definitions in the docker image inventory
```
openio_oioswift_users:
  - name: "demo:demo"
    password: "DEMO_PASS"
    roles:
      - admin

openio_oioswift_iam_policy:
  'demo:demo':
    Statement:
      - Sid: FullAccess
        Action:
          - 's3:*'
        Effect: Allow
        Resource:
          - '*'
```

You will have to play with the json file to modify the ACLs definition.

2020-05-18 17:18 UTC, cdelgehier requested changes
IAM is available in releases:
- 19.04
- 20.04
- 19.10 ? 
@murlock

2020-05-18 17:20 UTC, cdelgehier commented on openio-sds/18.10/openio-docker-init.sh
> +    # Insert "iam" before swift3 in pipeline's setup
And change the pipeline to
```
 openio_oioswift_pipeline: "{{ pipeline_tempauth_iam }}"
```

2020-05-18 17:43 UTC, dduportal commented on openio-sds/18.10/openio-docker-init.sh
> +    # Insert "iam" before swift3 in pipeline's setup
I have some concerns about expressing a default set of IAM policies:

- It feels weird to have a data structure expressed in YAML by default, that is overidden by a JSON struct (even though YAML is a super set of JSON). 

- How does it work when you provide custom rules: is it expected to be merged ? Or to override the default policy set?

But the idea of providing a default set with the system enabled is really appealing!

2020-05-26 07:49 UTC, murlock approved these changes

2020-05-26 07:49 UTC, murlock commented on openio-sds/19.04/openio-docker-init.sh
> +function iam_config(){
we forgot to add `s3_acl_openbar` (not sure if it is really an issue since we have only one user here)

2020-05-27 19:53 UTC, cdelgehier commented on openio-sds/19.04/openio-docker-init.sh
> +function iam_config(){
It s possible to define many users
`-e SWIFT_CREDENTIALS="admin:admin:admin:.admin .reseller_admin,test2:tester2:testing2:.admin,test5:tester5:testing5:service,test:tester:testing:.admin,test:tester3:testing3"`

2020-05-27 20:29 UTC, cdelgehier commented on openio-sds/18.10/openio-docker-init.sh
> +    # Insert "iam" before swift3 in pipeline's setup
* the yaml structure is only there for initial deployment (the general case)
* the user could provide his personal acl policy via environnement vars
```
environment :
   FOOBAR : '{"foo": "bar"}'
```
```
{
  "demo:demo": {
    "Statement": [
      {
        "Action": [
          "s3:*"
        ],
        "Effect": "Allow",
        "Resource": [
          "*"
        ],
        "Sid": "FullAccess"
      }
    ]
  },
  "mytenant:user1": {
    "Statement": [
      {
        "Action": [
          "s3:*"
        ],
        "Effect": "Allow",
        "Resource": [
          "*"
        ],
        "Sid": "FullAccess"
      }
    ]
  }
}
```

2020-05-28 07:05 UTC, cdelgehier commented on openio-sds/README.md
> +# docker run -d -e IAM_RULES_FILE='/etc/iam_rules.json' -v "$(pwd)/etc/iam_rules.json":/etc/iam_rules.json:ro openio/sds
YES !

2020-05-28 07:10 UTC, cdelgehier commented on openio-sds/README.md
> +# docker run -d -e IAM_RULES_FILE='/etc/iam_rules.json' -v "$(pwd)/etc/iam_rules.json":/etc/iam_rules.json:ro openio/sds
In the example, you should differentiate the paths. It's easier to understand than `$(pwd)/iam_rules.json` is that on the client side (and `/etc/iam_rules.json` in the container)

2020-05-28 07:12 UTC, cdelgehier commented on openio-sds/README.md
> +-e KEYSTONE_ENABLED='true' -e KEYSTONE_URI='172.17.0.3:5000' -e KEYSTONE_URL='172.17.0.3:35357'
🤔

2020-05-28 08:09 UTC, dduportal commented on openio-sds/19.04/openio-docker-init.sh
> +function iam_config(){
@cdelgehier if the user provides its own list of users, and enable IAM, then should we assume that an IAM rule must be provided?
Or should we test if no IAM rule file, then parse all users and set openbar acl to them ?

2020-05-28 08:23 UTC, dduportal commented on openio-sds/18.10/openio-docker-init.sh
> +    # Insert "iam" before swift3 in pipeline's setup
mmmh, I got the following thoughts

- As you saw, we intend to provide the IAM rules through a JSON file in the container, because providing JSON data structure through shell environment variable is a rabbit hole with tons of escapements to be made, and as a general rule of thumb should be avoided at all cost unless you are a shell master who has time to waste on this 😅

- Enabling IAM by default is a breaking change. I don't know how our Dockr images are used, and I agree that it is not a "production case". But if we do so, I would suggest to enable it by default only on 20.04, and keep 19.x (and 18.x eventually) with the current "IAM opt-in" behavior.

- Agreed with the default IAM rules, I understand it better with the explanation. I still have a case I'm not sure: If I launch a container (with IAM enabled by default) with this command:
`docker run -e SWIFT_CREDENTIALS="uberadmin:uberadmin" openio/sds:20.04`,
I understand that the default rule either:
  - Apply to the user `demo`, so my user `uberadmin` is not authroized to perform any action?
  - Apply to everyone: is it possible to set the target user to `*:*` ? And if yes, will this ACL be overriden by providing the IAM rule file ( e.g. `docker run -e SWIFT_CREDENTIALS="uberadmin:uberadmin" -e IAM_RULES_FILE='/etc/iam_rules.json' -v "$(pwd)/iam_rules.json":/etc/iam_rules.json:ro openio/sds:20.04`)? Or will it be merged ?

2020-10-05 12:19 UTC, cdelgehier commented
status ?

2020-10-05 12:31 UTC, dduportal commented
Aucune idée. Ping @murlock  est-ce que ce besoin existe toujours du côté dev ?

2020-10-09 12:53 UTC, murlock commented
If user provide list of users **and** IAM, please enable `s3_acl_openbar`

2020-10-16 07:40 UTC, cdelgehier commented
> If user provide list of users **and** IAM, please enable `s3_acl_openbar`

@dduportal this is an attribute of the middleware `swift3`

https://github.com/open-io/ansible-role-openio-oioswift/blob/20.04/defaults/main.yml#L175

2020-11-26 09:20 UTC, closed without merging